name: Sync PSN trophies

on:
  workflow_dispatch:

  schedule:
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"

concurrency:
  group: psn-trophy-sync
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Sync trophies
        id: sync
        continue-on-error: true
        env:
          PSN_NPSSO: ${{ secrets.PSN_NPSSO }}
        run: npm run sync

      - name: Commit changes
        run: |
          git config user.name "PSN Trophy Bot"
          git config user.email "actions@github.com"

          git add data/

          if git diff --cached --quiet; then
            echo "Aucun changement"
          else
            git commit -m "Update PSN trophies"
            git push
          fi

      - name: Fail workflow if sync failed
        if: steps.sync.outcome == 'failure'
        run: exit 1
